Update pull-request.yml

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -133,7 +133,19 @@ jobs:
       #   with:
       #     path: "./coverage/lcov.info"
       #     min_coverage: 0.0
-          
+
+  Check-Target-Branch:
+    if: ${{ github.actor != 'dependabot[bot]' }}
+    name: Check Target Branch
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check if the target branch is develop
+        if: github.event.pull_request.base.ref != 'develop'
+        run: |
+          echo "Error: Pull request target branch must be 'develop'. Please refer PR_GUIDELINES.md"
+          echo "Error: Close this PR and try again."
+          exit 1
+
   Validate-CodeRabbit:
     name: Validate CodeRabbit Approval
     runs-on: ubuntu-latest
